# Generated by Django 3.1 on 2020-08-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_demouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demouser',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
