# Generated by Django 3.1 on 2020-08-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20200819_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demouser',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demouser',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
