# Generated by Django 3.1 on 2020-08-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_auto_20200819_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected_User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_name', models.CharField(blank=True, max_length=30)),
                ('selected_address', models.CharField(blank=True, max_length=100)),
                ('selected_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
