# Generated by Django 3.1 on 2020-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_selected_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('exp_start_date', models.DateField(blank=True, null=True)),
                ('exp_end_date', models.DateField(blank=True, null=True)),
                ('is_working', models.BooleanField(default=False)),
            ],
        ),
    ]
