# Generated by Django 3.1 on 2020-08-19 12:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='welcome_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_email_id_from_anonymous_users', models.BooleanField(blank=True, default=False, null=True)),
                ('show_welcome_message_to_users', models.BooleanField(blank=True, default=False, null=True)),
                ('default_language', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Mandarin Chinese', 'Mandarin Chinese'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('Arabic', 'Arabic'), ('Bangla', 'Bangla'), ('Russian', 'Russian'), ('Portuguese', 'Portuguese'), ('Indonesian', 'Indonesian'), ('Urdu', 'Urdu')], max_length=87)),
                ('default_welcome_message', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('krishna', 'krishna'), ('gopal', 'gopal'), ('dubey', 'dubey'), ('ashutosh', 'ashutosh'), ('avinash', 'avinash')], max_length=36),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], max_length=10),
        ),
    ]
