# Generated by Django 3.1 on 2020-08-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_auto_20200819_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_urls', models.URLField()),
            ],
        ),
    ]
