# Generated by Django 3.1 on 2020-08-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_company_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_urls',
            name='company_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
