# Generated by Django 3.1 on 2020-08-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_company_urls_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Domain_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_Domain_Name', models.CharField(blank=True, max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company_urls',
            name='company_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='company_urls',
            name='company_urls',
            field=models.URLField(unique=True),
        ),
    ]
