# Generated by Django 3.1 on 2020-08-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0022_auto_20200820_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_configuration',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
