# Generated by Django 3.1 on 2020-08-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0023_auto_20200820_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome_messages',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.company_configuration'),
            preserve_default=False,
        ),
    ]
