# Generated by Django 3.1 on 2020-08-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0025_bot_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_dialog_flow_integration',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.bot_details'),
            preserve_default=False,
        ),
    ]
