# Generated by Django 3.1 on 2020-08-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0026_google_dialog_flow_integration_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='google_dialog_flow_integration',
            old_name='bid',
            new_name='bot_id',
        ),
    ]
